name: TUF-on-CI create Signing events

on:
  schedule:
    - cron:  '17 1,7,13,19 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  create-signing-events:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write' # for committing to signing event branch
      actions: 'write' # for dispatching signing event workflow
    steps:
      - name: Create signing events for offline version bumps
        uses: theupdateframework/tuf-on-ci/actions/create-signing-events@9319dd804f24ed81a02bea5e1c7edf5b0cdb9ba5
