name: Dump a JWT
on:
  workflow_dispatch:

jobs:
  dump:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: wtf jwt
        shell: bash
        run: |
           printf ${{ secrets.TUF_APP_ID }} | wc -c
