name: New Delegate Signing

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: ['sign/**']
    paths:
      - metadata/new-delegate.json
jobs:
  sign-and-push:
    name: TUF-on-CI New Delegate sign
    runs-on: ubuntu-latest
    permissions:
      contents: write # for making commits in signing event and for modifying draft state
      pull-requests: write # for modifying signing event pull requests
    steps:

      - name: Sign delegation
        uses: kommendorkapten/tuf-on-ci/actions/online-sign-targets@external-delegations
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID}}
        with:
          targets_to_sign: new-delegate
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
