name: TUF-on-CI online signing

permissions: {}

on:
  schedule:
    - cron:  '17 1,7,13,19 * * *'
  push:
    branches: [ main ]
    paths: ['metadata/**']
  workflow_dispatch:

jobs:
  online-sign:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write' # for OIDC identity access
      contents: 'write' # for commiting snapshot/timestamp changes
      actions: 'write' # for dispatching publish workflow

    steps:
      - id: online-sign
        uses: theupdateframework/tuf-on-ci/actions/online-sign@3491682aa226e159ddab4011df8009468cbf0dea
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID}}
        with:
          gcp_workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
