name: TUF-on-CI online signing

permissions: {}

on:
  schedule:
    - cron:  '17 1,7,13,19 * * *'
  push:
    branches: [ main ]
    paths: ['metadata/**', '!metadata/timestamp.json', '!metadata/snapshot.json']
  workflow_dispatch:

jobs:
  online-sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write' # for OIDC identity access
      contents: 'write' # for commiting snapshot/timestamp changes
      actions: 'write' # for dispatching publish workflow
    steps:
      - name: Generate app token
        id: generate-token
        uses: actions/create-github-app-token@e995b4e40ace2eb5bf13137d9abe242c98f3aab6
        with:
          app-id: ${{ secrets.TUF_APP_ID }}
          private-key: ${{ secrets.TUF_APP_PRIVATE_KEY}}
          repositories: tuf-repo-test-4
      - id: online-sign
        uses: theupdateframework/tuf-on-ci/actions/online-sign@c5db84288ae27ca64c03623975e2cc2723715203
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID}}
        with:
          # token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          token: ${{ steps.generate_token.outputs.token }}
          gcp_workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}


  update-issue:
    runs-on: ubuntu-latest
    needs: [online-sign]
    if: always() && !cancelled()
    permissions:
      issues: 'write' # for modifying Issues
    steps:
      - name: Update the issue for the workflow
        uses: theupdateframework/tuf-on-ci/actions/update-issue@c5db84288ae27ca64c03623975e2cc2723715203
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
