name: TUF-on-CI signing event

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: ['sign/**']
    paths: ['metadata/**', 'targets/**']

jobs:
  handle-signing-event:
    name: TUF-on-CI signing event
    runs-on: ubuntu-latest
    permissions:
      contents: write # for making commits in signing event and for modifying draft state
      pull-requests: write # for modifying signing event pull requests
      actions: write # for dispatching another signing-event workflow

    steps:
      - name: Signing event
        uses: kommendorkapten/tuf-on-ci/actions/signing-event@50cca7b5149aa1f2166798241fb99bbc8f5fabd4
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
