name: TUF-on-CI signing event

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: ['sign/**']
    paths: ['metadata/**', 'targets/**']

jobs:
  handle-signing-event:
    name: TUF-on-CI signing event
    runs-on: ubuntu-latest
    permissions:
      contents: write # for adding targets changes into the signing event branch
      issues: write
      actions: write # for dispatching another signing-event workflow
      pull-requests: write

    steps:
      - name: Signing event
        uses: theupdateframework/tuf-on-ci/actions/signing-event@f31ef4f7dd38d2b531e5db3668e6a2e8d57c718b
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
