name: TUF-on-CI signing event

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: ['sign/**']


jobs:
  handle-signing-event:
    name: TUF-on-CI signing event
    runs-on: ubuntu-latest
    permissions:
      contents: write # for making commits in signing event and for modifying draft state
      pull-requests: write # for modifying signing event pull requests
      actions: write # for dispatching another signing-event workflow

    steps:
      - name: Signing event
        uses: kommendorkapten/tuf-on-ci/actions/signing-event@external-delegations
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}

      - name: foo
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const result = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: context.sha
            })
            console.log(result)
