name: TUF-on-CI signing event

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: ['sign/**']
    paths: ['metadata/**', 'targets/**']

jobs:
  handle-signing-event:
    name: TUF-on-CI signing event
    runs-on: ubuntu-latest
    permissions:
      contents: write # for adding targets changes into the signing event branch
      issues: write
    steps:
      - name: Signing event
        uses: theupdateframework/tuf-on-ci/actions/signing-event@5875ebd693d5a9c4496c4669d81763e9d264dd6f
